### ISSUE TITLE
Dogfooding / Testing

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#267]
# Dogfooding/Testing
We are testing the key features of our app, specifically the food image recognition, social aspects, and the breakdown screens. 

## Where to find our app

https://expo.dev/@qspraut/macro-frontend

Download Expo Go on your phone and scan the QR code at the link above

## Onboarding
1. Open the app from expo
2. Click through the sign up screens

__Q: Is there anything confusing or unintuitive about the onboarding process?__

## Food recognition:
1. Take photo of the food (single foods only - our app is currently trained for some fruits and vegetables but will be expanding soon)
2. Fill out the form that pops up after the image
3. Look through the food breakdown of the various macros

__Q: Was there anything interesting or confusing about the form?__
__Q: Did the app provide enough feedback during the process, like photo was taken, submission was successful etc.?__
__Q: Did the breakdown screen provide useful information? and was it intuitive to understand?__
__Q: Was the classification and calorie estimation accurate?__

## History 
1. Scroll through the different meals that you have photographed
2. Heart or delete certain photos

__Q: Is there anything you feel is missing from the history screen?__

## Community tab:
1. Like a food item
2. Navigate through the tabs
3. Click on and expand a food item
__Q: Is there anything you feel is missing from the community screen?__
__Q: Did you find the tab system helpful / intuitive?__

# Bug Reports
_please list any bug reports and attach screenshots here_

**Comment by laureldernbach** [comment]
did the link expire? the one to Expo works but once there the QR code/link invitation seems to be a dud

**Comment by grantrdumanian** [comment]
^^^ seconding this!

**Comment by qspraut** [comment]
@laureldernbach @grantrdumanian  looking into this

**Comment by qspraut** [comment]
@laureldernbach @grantrdumanian do you have Expo Go installed on your phone? The QR code seems to be working fine for me

**Comment by laureldernbach** [comment]
oh no, let me try that!

**Comment by qspraut** [comment]
Just as a heads up, the first time you try to log in / classify a food it may be a bit slow since the servers are waking up!

**Comment by laureldernbach** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/65263014/154871493-1adeed1a-0f77-460a-a692-8174fd1b9589.png)
from the Expo app

**Comment by qspraut** [comment]
@laureldernbach @grantrdumanian Sorry about this! It turns out that publishing the app via expo does not allow other users to test it out, which is contrary to what I thought since I was able to access it as the publisher just fine.

We will get this uploaded to testflight tomorrow (I believe we need to get in contact with Tim to do so), and I hope you guys would still be willing to give the app a bit of a trial run for us after that. Sorry for the inconvenience!

CC @timofei7 @romano-w

**Comment by laureldernbach** [comment]
Onboarding
Q: Is there anything confusing or unintuitive about the onboarding process?

- No, nothing confusing about onboarding! The servers didn't even take that long to boot up for me. My one comment here is that the "remember me" checkbox doesn't seem to be doing anything -- I have had to enter my email every time I open the app to document a meal.

Food recognition:
Q: Was there anything interesting or confusing about the form?

-Yes, I am kind of confused how the simple/complex options work. I never quite got the hang of it, but ultimately the complex documented seemed more practical to me because the simple, auto-generated information was not accurate.

Q: Did the app provide enough feedback during the process, like photo was taken, submission was successful etc.?

- Generally yes, I am confused a little by the community tag -- who's stuff am I seeing? My friends? People in my geographic vicinity? All-time users? That being said I wanted my own entries to show up under the community tab-- it was kind of counter intuitive to me that my personal logs were separate from the "community/friends" feed

Q: Did the breakdown screen provide useful information? and was it intuitive to understand?

- Yes, the information provided was useful and intuitive. Could be cool to include more information about daily caloric intake/a balanced diet.

Q: Was the classification and calorie estimation accurate?

- Classification, no. Calories estimation was more accurate than I expected but still not great-- for example I had a bagel with tahini for a lunch that was probably 350+ calories total but it estimated 173.

History
Q: Is there anything you feel is missing from the history screen?

- This was all good

Community tab:

Q: Is there anything you feel is missing from the community screen?

- Options for comments/interaction between users could be cool. Again, some sense of 'ownership' over a post could be cool -- at least to see who posted what.

Q: Did you find the tab system helpful / intuitive?

- yes, again I think it might make sense to have a 'personal history' tab here -- kind of like Venmo.

Bug Reports

- A few UI comments, some of your boxes/text align kind of funky. I wish ass the text fit more neatly in the boxes
- 
![IMG_1927](https://user-images.githubusercontent.com/65263014/155906797-e66c5a96-187f-4e39-bb87-f0f45ac59438.PNG)

- Also, the 'related foods' on the expanded view are not super helpful nor relevant. They are distracting to me.
- 
![IMG_1926](https://user-images.githubusercontent.com/65263014/155906847-19631078-201e-4320-a7bc-0c1d0c3775e2.PNG)

**Comment by grantrdumanian** [comment]
Q: Is there anything confusing or unintuitive about the onboarding process?
* Nope! Logging in was pretty easy.

Q: Was there anything interesting or confusing about the form?
* The mood was a little confusing, mostly because I don’t really know how it factors into food classification at all. The “simple” and “complex” buttons were also kind of hard to see, I almost missed them.;

Q: Did the app provide enough feedback during the process, like photo was taken, submission was successful etc.?
* I wasn’t able to get a food classified ): Every time I tried to click submit, I got a message saying “still classifying… try again in a moment!”

Q: Did the breakdown screen provide useful information? and was it intuitive to understand?
* Again, I did not get a classification. When I looked at a classmate’s breakdown, the food was incorrect (pita chip classified as an onion) but the information about the onion looked on point! It was all easy to read.

Q: Was the classification and calorie estimation accurate?
* The classification was inaccurate, but it looked like the calorie estimation for the inacurate classification might be accurate.

Q: Is there anything you feel is missing from the history screen?
* The “related foods” look like they might be hardcoded? Also, I think some sort of timestamp for when the meal was photographed might be helpful! It is unclear how the entries are organized.

Q: Is there anything you feel is missing from the community screen?
* I “favorited” something but it did not show up in the favorites tab. It might also be helpful to have some sort of indication of who posted what food.

Q: Did you find the tab system helpful / intuitive?
* I liked the tab system! It wasn’t always clear what each button was for, but I felt like I was able to navigate around the app easily.

Bug Screenshots:
* Text outside of box
![](https://i.imgur.com/1qagKo7.png)

* Favorites not working
![](https://i.imgur.com/8Lbr4HM.png)
![](https://i.imgur.com/D5VgUO3.png)

**Comment by kattaylor22** [comment]
# Onboarding
**Q: Is there anything confusing or unintuitive about the onboarding process?**
Onboarding was super and easy and intuitive! It is kind of annoying to have to sign in each time, but I get it if it's required somehow.

# Food recognition:
**Q: Was there anything interesting or confusing about the form?**
I found the current mood section interesting/not intuitive as to why it was there. Does this somehow go into the algorithm? Or does it ever get posted on the community board? Its purpose is unclear to me.

**Q: Did the app provide enough feedback during the process, like photo was taken, submission was successful etc.?**
Yes!

**Q: Did the breakdown screen provide useful information? and was it intuitive to understand?**
Definitely intuitive to understand and held useful (although maybe not the most accurate) information

**Q: Was the classification and calorie estimation accurate?**
No.

# History
**Q: Is there anything you feel is missing from the history screen?**
No - I like it and its intuitive! One thing is that sometimes the UI gets messed up in the expanded view and the title of the food overlaps with the box of detailed breakdown. Grant's screenshot above is the same issue I'm finding.

# Community tab:
**Q: Is there anything you feel is missing from the community screen?**
No, I like it!

**Q: Did you find the tab system helpful / intuitive?**
Definitely intuitive. Although I'm not sure what the "favorite" tab is supposed to be displaying. It doesn't seem to be showing items I have favorited (and is showing items that I know I have not favorited).


# Bug Reports
The keyboard does not automatically go away when typing in the text boxes both on the complex form and in the onboarding/log in flow. So rather than going away when I tap elsewhere on the screen, the keyboard stays up until I tap return, which I find a little frustrating.

Also, the related foods in the expanded view seem to be the same no matter the item of food and also very specific food items. I honestly think it may be better to scrap that section rather than show the same specific suggestions each time.
